In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## Define the vocabulary size
voc_size=10000

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8353, 9781, 4045, 2923],
 [8353, 9781, 4045, 6033],
 [8353, 7412, 4045, 9250],
 [4671, 9967, 5778, 2902, 1236],
 [4671, 9967, 5778, 2902, 675],
 [8751, 8353, 3410, 4045, 2871],
 [2371, 5618, 588, 2902]]

In [13]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8353 9781 4045 2923]
 [   0    0    0    0 8353 9781 4045 6033]
 [   0    0    0    0 8353 7412 4045 9250]
 [   0    0    0 4671 9967 5778 2902 1236]
 [   0    0    0 4671 9967 5778 2902  675]
 [   0    0    0 8751 8353 3410 4045 2871]
 [   0    0    0    0 2371 5618  588 2902]]


In [16]:
## feature representation
dim=10

In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 10)          100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 20ms/step


array([[[ 0.00916121,  0.03145018,  0.04208547, -0.00752525,
         -0.02108176, -0.02602402, -0.02952062, -0.03402986,
         -0.0378459 , -0.01221074],
        [ 0.00916121,  0.03145018,  0.04208547, -0.00752525,
         -0.02108176, -0.02602402, -0.02952062, -0.03402986,
         -0.0378459 , -0.01221074],
        [ 0.00916121,  0.03145018,  0.04208547, -0.00752525,
         -0.02108176, -0.02602402, -0.02952062, -0.03402986,
         -0.0378459 , -0.01221074],
        [ 0.00916121,  0.03145018,  0.04208547, -0.00752525,
         -0.02108176, -0.02602402, -0.02952062, -0.03402986,
         -0.0378459 , -0.01221074],
        [ 0.03782696, -0.01711203,  0.0499226 ,  0.04648041,
          0.02599821, -0.00770249, -0.02454102, -0.02155696,
         -0.03874675,  0.02273157],
        [ 0.00625467, -0.02661345,  0.0003271 ,  0.00842463,
         -0.04028568,  0.01748784, -0.00661354, -0.01655968,
          0.04743961,  0.02971711],
        [-0.01547328, -0.04903911, -0.04805489,  0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 8353, 9781, 4045, 2923])

In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 35ms/step


array([[ 0.00916121,  0.03145018,  0.04208547, -0.00752525, -0.02108176,
        -0.02602402, -0.02952062, -0.03402986, -0.0378459 , -0.01221074],
       [ 0.00916121,  0.03145018,  0.04208547, -0.00752525, -0.02108176,
        -0.02602402, -0.02952062, -0.03402986, -0.0378459 , -0.01221074],
       [ 0.00916121,  0.03145018,  0.04208547, -0.00752525, -0.02108176,
        -0.02602402, -0.02952062, -0.03402986, -0.0378459 , -0.01221074],
       [ 0.00916121,  0.03145018,  0.04208547, -0.00752525, -0.02108176,
        -0.02602402, -0.02952062, -0.03402986, -0.0378459 , -0.01221074],
       [ 0.03782696, -0.01711203,  0.0499226 ,  0.04648041,  0.02599821,
        -0.00770249, -0.02454102, -0.02155696, -0.03874675,  0.02273157],
       [ 0.00625467, -0.02661345,  0.0003271 ,  0.00842463, -0.04028568,
         0.01748784, -0.00661354, -0.01655968,  0.04743961,  0.02971711],
       [-0.01547328, -0.04903911, -0.04805489,  0.04020092,  0.04861439,
         0.016951  , -0.01735265, -0.02973055